name: Build Flutter APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Clone repository
      uses: actions/checkout@v4

    # Set up Java 17
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    # Set up Flutter with specific version
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.32.7  # Specify Flutter version explicitly
        channel: stable          # Use the stable channel

    # Install Flutter dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build APK
    - name: Build APK
      run: flutter build apk --release

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk
